### PR TITLE
Fix: Siema import

### LINKED ISSUE #73: SyntaxError: The requested module 'siema' does not provide an export named 'default'
https://github.com/beyonk-adventures/svelte-carousel/blob/37cb1b6437c80dca8b7cc3a1d8ee9c088d668485/src/Carousel.svelte#L82

Error Detail :
SyntaxError: The requested module '/node_modules/siema/dist/siema.min.js?v=119354d5' does not provide an export named 'default'

### PR DESCRIPTION
**Pull request by basaran**
closes #73

### CODE REVIEW

**Comment by basaran** [comment]
We will also need you to update the npm package please :)

**Comment by eur2** [comment]
@antony Is it possible to merge this commit to update the npm package? That would make this carousel working with sveltekit. Thanks a lot!

**Review by antony — APPROVED** [review]

**Comment by eur2** [comment]
@antony thank you! Is this new version already available on npm?

**Comment by eur2** [comment]
Thank you! Now it's working great with sveltekit

**Pull request merged**
